# Generated by Django 2.0.6 on 2018-07-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('gu_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to='files/')),
                ('filename', models.CharField(max_length=255)),
                ('total_page', models.PositiveIntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='date file uploaded')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('file_share_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_file_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File')),
                ('sharer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_file_sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_share_group', to='user.File')),
                ('shared_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_file', to='user.File')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File')),
                ('shared_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=255)),
                ('coordinate', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('editor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('labeled_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cellphone', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
