# Generated by Django 2.0.6 on 2018-07-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='share_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
        ),
    ]
