# Generated by Django 2.0.6 on 2018-08-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180726_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfiles',
            name='share_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_share_group', to='user.Group'),
        ),
    ]
