# Generated by Django 2.0.6 on 2018-08-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180807_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='user.Group'),
        ),
    ]
