# Generated by Django 2.0.6 on 2018-08-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fileshare_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
