# Generated by Django 2.0.6 on 2018-08-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_group_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileshare',
            name='type',
        ),
    ]
